/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ContentFolder', 'model/ContentFolderResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ContentFolder'), require('../model/ContentFolderResult'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.FoldersApi = factory(root.ShopApi.ApiClient, root.ShopApi.ContentFolder, root.ShopApi.ContentFolderResult);
  }
}(this, function(ApiClient, ContentFolder, ContentFolderResult) {
  'use strict';

  /**
   * Folders service.
   * @module api/FoldersApi
   * @version 17.3
   */

  /**
   * Constructs a new FoldersApi. 
   * @alias module:api/FoldersApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getFoldersByID operation.
     * @callback module:api/FoldersApi~getFoldersByIDCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContentFolder} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * To access a content folder, you construct a URL using the template shown below. This template requires you to  specify a content folder id and a subfolder level. In response, the server returns a corresponding content  folder document. Only content folder, which are marked as online are returned.
     * @param {String} id The id of the requested content folder.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.levels 
     * @param {String} opts.locale 
     * @param {module:api/FoldersApi~getFoldersByIDCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContentFolder}
     */
    this.getFoldersByID = function(id, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw new Error("Missing the required parameter 'id' when calling getFoldersByID");
      }


      var pathParams = {
        'id': id
      };
      var queryParams = {
        'levels': opts['levels'],
        'locale': opts['locale']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['customers_auth', 'client_id'];
      var contentTypes = ['application/json', 'text/xml', 'application/xml'];
      var accepts = ['application/json', 'text/xml', 'application/xml'];
      var returnType = ContentFolder;

      return this.apiClient.callApi(
        '/folders/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getFoldersByIDs operation.
     * @callback module:api/FoldersApi~getFoldersByIDsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ContentFolderResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Array.<String>} ids 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.levels 
     * @param {String} opts.locale 
     * @param {module:api/FoldersApi~getFoldersByIDsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/ContentFolderResult}
     */
    this.getFoldersByIDs = function(ids, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'ids' is set
      if (ids == undefined || ids == null) {
        throw new Error("Missing the required parameter 'ids' when calling getFoldersByIDs");
      }


      var pathParams = {
        'ids': ids
      };
      var queryParams = {
        'levels': opts['levels'],
        'locale': opts['locale']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['customers_auth', 'client_id'];
      var contentTypes = ['application/json', 'text/xml', 'application/xml'];
      var accepts = ['application/json', 'text/xml', 'application/xml'];
      var returnType = ContentFolderResult;

      return this.apiClient.callApi(
        '/folders/({ids})', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
