/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PriceAdjustmentLimits'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/PriceAdjustmentLimits'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.PriceAdjustmentLimitsApi = factory(root.ShopApi.ApiClient, root.ShopApi.PriceAdjustmentLimits);
  }
}(this, function(ApiClient, PriceAdjustmentLimits) {
  'use strict';

  /**
   * PriceAdjustmentLimits service.
   * @module api/PriceAdjustmentLimitsApi
   * @version 17.3
   */

  /**
   * Constructs a new PriceAdjustmentLimitsApi. 
   * @alias module:api/PriceAdjustmentLimitsApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getPriceAdjustmentLimits operation.
     * @callback module:api/PriceAdjustmentLimitsApi~getPriceAdjustmentLimitsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PriceAdjustmentLimits} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Returns a list of price adjustment limits for the authenticated user and the site defined in the URL.    At least one of the following functional permissions must be assigned to the user to be able to access it:  Adjust_Item_Price or Adjust_Shipping_Price or Adjust_Order_Price.  
     * @param {module:api/PriceAdjustmentLimitsApi~getPriceAdjustmentLimitsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PriceAdjustmentLimits}
     */
    this.getPriceAdjustmentLimits = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['customers_auth', 'oauth2_application'];
      var contentTypes = ['application/json', 'text/xml', 'application/xml'];
      var accepts = ['application/json', 'text/xml', 'application/xml'];
      var returnType = PriceAdjustmentLimits;

      return this.apiClient.callApi(
        '/PriceAdjustmentLimits', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
