/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SuggestionResult'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/SuggestionResult'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.SearchSuggestionApi = factory(root.ShopApi.ApiClient, root.ShopApi.SuggestionResult);
  }
}(this, function(ApiClient, SuggestionResult) {
  'use strict';

  /**
   * SearchSuggestion service.
   * @module api/SearchSuggestionApi
   * @version 17.3
   */

  /**
   * Constructs a new SearchSuggestionApi. 
   * @alias module:api/SearchSuggestionApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getSearchSuggestion operation.
     * @callback module:api/SearchSuggestionApi~getSearchSuggestionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuggestionResult} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Provides keyword search functionality for products, categories, content, brands and custom suggestions.  Returns suggested products, suggested categories, suggested content, suggested brands and custom suggestions  for the given search phrase.
     * @param {String} q The query phrase to search for.
     * @param {Object} opts Optional parameters
     * @param {Number} opts.count The maximum number of suggestions per request. Default value is 5. This affects all types of suggestions (category, product, content, brand, custom suggestions).
     * @param {String} opts.currency The currency mnemonic specified for price. This parameter is effective only for product suggestions.
     * @param {String} opts.locale 
     * @param {module:api/SearchSuggestionApi~getSearchSuggestionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuggestionResult}
     */
    this.getSearchSuggestion = function(q, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'q' is set
      if (q == undefined || q == null) {
        throw new Error("Missing the required parameter 'q' when calling getSearchSuggestion");
      }


      var pathParams = {
      };
      var queryParams = {
        'q': q,
        'count': opts['count'],
        'currency': opts['currency'],
        'locale': opts['locale']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['customers_auth', 'client_id'];
      var contentTypes = ['application/json', 'text/xml', 'application/xml'];
      var accepts = ['application/json', 'text/xml', 'application/xml'];
      var returnType = SuggestionResult;

      return this.apiClient.callApi(
        '/SearchSuggestion', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
