/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Customer'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Customer'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.CustomerRegistration = factory(root.ShopApi.ApiClient, root.ShopApi.Customer);
  }
}(this, function(ApiClient, Customer) {
  'use strict';




  /**
   * The CustomerRegistration model module.
   * @module model/CustomerRegistration
   * @version 17.3
   */

  /**
   * Constructs a new <code>CustomerRegistration</code>.
   * Document representing the registration information for a customer.
   * @alias module:model/CustomerRegistration
   * @class
   * @param customer {module:model/Customer} The customer registration information.  The mandatory properties for registration are login, last name and email.
   */
  var exports = function(customer) {
    var _this = this;

    _this['customer'] = customer;

  };

  /**
   * Constructs a <code>CustomerRegistration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomerRegistration} obj Optional instance to populate.
   * @return {module:model/CustomerRegistration} The populated <code>CustomerRegistration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('customer')) {
        obj['customer'] = Customer.constructFromObject(data['customer']);
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
    }
    return obj;
  }

  /**
   * The customer registration information.  The mandatory properties for registration are login, last name and email.
   * @member {module:model/Customer} customer
   */
  exports.prototype['customer'] = undefined;
  /**
   * The password to authorize.
   * @member {String} password
   */
  exports.prototype['password'] = undefined;



  return exports;
}));


