/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Query'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Query'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.NestedQuery = factory(root.ShopApi.ApiClient, root.ShopApi.Query);
  }
}(this, function(ApiClient, Query) {
  'use strict';




  /**
   * The NestedQuery model module.
   * @module model/NestedQuery
   * @version 17.3
   */

  /**
   * Constructs a new <code>NestedQuery</code>.
   * @alias module:model/NestedQuery
   * @class
   * @param path {String} 
   * @param query {module:model/Query} 
   */
  var exports = function(path, query) {
    var _this = this;

    _this['path'] = path;
    _this['query'] = query;

  };

  /**
   * Constructs a <code>NestedQuery</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NestedQuery} obj Optional instance to populate.
   * @return {module:model/NestedQuery} The populated <code>NestedQuery</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('path')) {
        obj['path'] = ApiClient.convertToType(data['path'], 'String');
      }
      if (data.hasOwnProperty('query')) {
        obj['query'] = Query.constructFromObject(data['query']);
      }
      if (data.hasOwnProperty('score_mode')) {
        obj['score_mode'] = ApiClient.convertToType(data['score_mode'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} path
   */
  exports.prototype['path'] = undefined;
  /**
   * @member {module:model/Query} query
   */
  exports.prototype['query'] = undefined;
  /**
   * @member {module:model/NestedQuery.ScoreModeEnum} score_mode
   */
  exports.prototype['score_mode'] = undefined;


  /**
   * Allowed values for the <code>score_mode</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ScoreModeEnum = {
    /**
     * value: "avg"
     * @const
     */
    "avg": "avg",
    /**
     * value: "total"
     * @const
     */
    "total": "total",
    /**
     * value: "max"
     * @const
     */
    "max": "max",
    /**
     * value: "none"
     * @const
     */
    "none": "none"  };


  return exports;
}));


