/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Order'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Order'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.OrderSearchHit = factory(root.ShopApi.ApiClient, root.ShopApi.Order);
  }
}(this, function(ApiClient, Order) {
  'use strict';




  /**
   * The OrderSearchHit model module.
   * @module model/OrderSearchHit
   * @version 17.3
   */

  /**
   * Constructs a new <code>OrderSearchHit</code>.
   * Document representing an order search hit.
   * @alias module:model/OrderSearchHit
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>OrderSearchHit</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderSearchHit} obj Optional instance to populate.
   * @return {module:model/OrderSearchHit} The populated <code>OrderSearchHit</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('data')) {
        obj['data'] = Order.constructFromObject(data['data']);
      }
      if (data.hasOwnProperty('relevance')) {
        obj['relevance'] = ApiClient.convertToType(data['relevance'], 'Number');
      }
    }
    return obj;
  }

  /**
   * 
   * @member {module:model/Order} data
   */
  exports.prototype['data'] = undefined;
  /**
   * The hit's relevance score.
   * @member {Number} relevance
   */
  exports.prototype['relevance'] = undefined;



  return exports;
}));


