/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Query'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Query'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.QueryFilter = factory(root.ShopApi.ApiClient, root.ShopApi.Query);
  }
}(this, function(ApiClient, Query) {
  'use strict';




  /**
   * The QueryFilter model module.
   * @module model/QueryFilter
   * @version 17.3
   */

  /**
   * Constructs a new <code>QueryFilter</code>.
   * Document representing a query filter. A query filter wraps any query and allows it to be used as a filter.  
   * @alias module:model/QueryFilter
   * @class
   * @param query {module:model/Query} The query, which should be used as a filter.
   */
  var exports = function(query) {
    var _this = this;

    _this['query'] = query;
  };

  /**
   * Constructs a <code>QueryFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/QueryFilter} obj Optional instance to populate.
   * @return {module:model/QueryFilter} The populated <code>QueryFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('query')) {
        obj['query'] = Query.constructFromObject(data['query']);
      }
    }
    return obj;
  }

  /**
   * The query, which should be used as a filter.
   * @member {module:model/Query} query
   */
  exports.prototype['query'] = undefined;



  return exports;
}));


