/**
 * Shop API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 17.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ShopApi) {
      root.ShopApi = {};
    }
    root.ShopApi.RangeFilter = factory(root.ShopApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The RangeFilter model module.
   * @module model/RangeFilter
   * @version 17.3
   */

  /**
   * Constructs a new <code>RangeFilter</code>.
   * Document representing a range filter.  
   * @alias module:model/RangeFilter
   * @class
   * @param field {String} The search field.
   */
  var exports = function(field) {
    var _this = this;

    _this['field'] = field;




  };

  /**
   * Constructs a <code>RangeFilter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RangeFilter} obj Optional instance to populate.
   * @return {module:model/RangeFilter} The populated <code>RangeFilter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('field')) {
        obj['field'] = ApiClient.convertToType(data['field'], 'String');
      }
      if (data.hasOwnProperty('from')) {
        obj['from'] = ApiClient.convertToType(data['from'], Object);
      }
      if (data.hasOwnProperty('from_inclusive')) {
        obj['from_inclusive'] = ApiClient.convertToType(data['from_inclusive'], 'Boolean');
      }
      if (data.hasOwnProperty('to')) {
        obj['to'] = ApiClient.convertToType(data['to'], Object);
      }
      if (data.hasOwnProperty('to_inclusive')) {
        obj['to_inclusive'] = ApiClient.convertToType(data['to_inclusive'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * The search field.
   * @member {String} field
   */
  exports.prototype['field'] = undefined;
  /**
   * The configured lower bound of the filter range. The lower bound is optional. If not given, the range is  open ended with respect to the lower bound.
   * @member {Object} from
   */
  exports.prototype['from'] = undefined;
  /**
   * A flag indicating whether the lower bound of the range is inclusive (or exclusive). The default is true (which means that the given  lower bound is inclusive).
   * @member {Boolean} from_inclusive
   */
  exports.prototype['from_inclusive'] = undefined;
  /**
   * The configured upper bound of the filter range. The upper bound is optional. If not given, the range is  open ended with respect to the upper bound.
   * @member {Object} to
   */
  exports.prototype['to'] = undefined;
  /**
   * A flag indicating whether the upper bound of the range is inclusive (or exclusive). The default is true (which means that the given  upper bound is inclusive).
   * @member {Boolean} to_inclusive
   */
  exports.prototype['to_inclusive'] = undefined;



  return exports;
}));


